{
    "openapi": "3.0.0",
    "info": {
      "title": "Textiles API",
      "description": "API con NodeJS y Express",
      "version": "1.0.0",
      "license": {
        "name": "MIT",
        "url": "https://opensource.org/licenses/MIT"
      }
    },
    "servers": [
      {
        "url": ""
      }
    ],
    "components": {
      "securitySchemes": {
        "bearerAuth": {
          "type": "http",
          "scheme": "bearer"
        }
      }
    },
    "tags": [
      {
        "name": "Carts"
      },
      {
        "name": "Categories"
      },
      {
        "name": "Orders"
      },
      {
        "name": "Products"
      },
      {
        "name": "Users"
      }
    ],
    "paths": {
      "/cart": {
        "get": {
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "tags": [
            "Carts"
          ],
          "summary": "Return Carts by User Token",
          "responses": {
            "200": {
              "description": "Successful response",
              "content": {
                "application/json": {}
              }
            }
          }
        },
        "post": {
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "tags": [
            "Carts"
          ],
          "summary": "Create Cart",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "productId": 1,
                    "quantity": 1,
                    "size": "",
                    "color": ""
                  }
                }
              }
            }
          },
          "responses": {
            "201": {
              "description": "Successful response",
              "content": {
                "application/json": {}
              }
            }
          }
        }
      },
      "/cart/{itemId}": {
        "parameters": [
          {
            "name": "itemId",
            "in": "path",
            "description": "Unique identifier of the group.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "put": {
          "tags": [
            "Carts"
          ],
          "summary": "Update Item by ID",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "productId": "productId",
                    "quantity": "quantity",
                    "size": "size",
                    "color": "color",
                    "user": {
                      "hola": "hola"
                    }
                  }
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Successful response",
              "content": {
                "application/json": {}
              }
            }
          }
        },
        "delete": {
          "tags": [
            "Carts"
          ],
          "summary": "Delete Item by ID",
          "responses": {
            "200": {
              "description": "Successful response",
              "content": {
                "application/json": {}
              }
            }
          }
        }
      },
      "/categories": {
        "get": {
          "tags": [
            "Categories"
          ],
          "summary": "Return All Categories",
          "responses": {
            "200": {
              "description": "Successful response",
              "content": {
                "application/json": {}
              }
            }
          }
        },
        "post": {
          "tags": [
            "Categories"
          ],
          "summary": "Create Category",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "cat_name": "",
                    "cat_desc": "",
                    "cat_img": ""
                  }
                }
              }
            }
          },
          "responses": {
            "201": {
              "description": "Successful response",
              "content": {
                "application/json": {}
              }
            }
          }
        }
      },
      "/categories/{id}": {
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Unique identifier of the group.",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "get": {
          "tags": [
            "Categories"
          ],
          "summary": "Return Category by ID",
          "responses": {
            "200": {
              "description": "Successful response",
              "content": {
                "application/json": {}
              }
            }
          }
        },
        "put": {
          "tags": [
            "Categories"
          ],
          "summary": "Update Category by ID",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "cat_name": "",
                    "cat_desc": "",
                    "cat_img": "",
                    "categoryId": ""
                  }
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Successful response",
              "content": {
                "application/json": {}
              }
            }
          }
        },
        "delete": {
          "tags": [
            "Categories"
          ],
          "summary": "Delete Category by ID",
          "responses": {
            "200": {
              "description": "Successful response",
              "content": {
                "application/json": {}
              }
            }
          }
        }
      },
      "/place-order": {
        "post": {
          "tags": [
            "Orders"
          ],
          "summary": "Place Order",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "userdId": "userId"
                  }
                }
              }
            }
          },
          "responses": {
            "201": {
              "description": "Successful response",
              "content": {
                "application/json": {}
              }
            }
          }
        }
      },
      "/categories/{id}/products": {
        "get": {
          "tags": [
            "Products"
          ],
          "summary": "Return All Products by Category ID",
          "parameters": [
            {
              "name": "id",
              "in": "path",
              "description": "Unique identifier of the group.",
              "required": true,
              "schema": {
                "type": "integer",
                "format": "int64"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "Successful response",
              "content": {
                "application/json": {}
              }
            }
          }
        },
        "post": {
          "tags": [
            "Products"
          ],
          "summary": "Create Product in the ID indicated by category",
          "parameters": [
            {
              "name": "id",
              "in": "path",
              "description": "Unique identifier of the group.",
              "required": true,
              "schema": {
                "type": "integer",
                "format": "int64"
              }
            }
          ],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "prod_name": "",
                    "prod_type": "",
                    "prod_size": "",
                    "prod_color": "",
                    "prod_price": "",
                    "prod_topic": "",
                    "prod_designer": "",
                    "prod_img": ""
                  }
                }
              }
            }
          },
          "responses": {
            "201": {
              "description": "Successful response",
              "content": {
                "application/json": {}
              }
            }
          }
        }
      },
      "/categories/{catId}/products/{prodId}": {
        "parameters": [
          {
            "name": "catId",
            "in": "path",
            "description": "Unique identifier of the group.",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          },
          {
            "name": "prodId",
            "in": "path",
            "description": "Unique identifier of the group.",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "get": {
          "tags": [
            "Products"
          ],
          "summary": "Devolver product by ID and category ID",
          "responses": {
            "200": {
              "description": "Successful response",
              "content": {
                "application/json": {}
              }
            }
          }
        },
        "put": {
          "tags": [
            "Products"
          ],
          "summary": "Update Product",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "prod_name": "",
                    "prod_type": "",
                    "prod_size": "",
                    "prod_color": "",
                    "prod_price": "",
                    "prod_topic": "",
                    "prod_designer": "",
                    "prod_img": ""
                  }
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Successful response",
              "content": {
                "application/json": {}
              }
            }
          }
        },
        "delete": {
          "tags": [
            "Products"
          ],
          "summary": "Delete Product",
          "responses": {
            "200": {
              "description": "Successful response",
              "content": {
                "application/json": {}
              }
            }
          }
        }
      },
      "/mercado-pago-notifications": {
        "post": {
          "tags": [
            "Orders"
          ],
          "summary": "Notifications mercado pago test",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "userdId": "userId"
                  }
                }
              }
            }
          },
          "responses": {
            "201": {
              "description": "Successful response",
              "content": {
                "application/json": {}
              }
            }
          }
        }
      },
      "/validate-user": {
        "post": {
          "tags": [
            "Users"
          ],
          "summary": "Validate User",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "token": ""
                  }
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Succesfull Response",
              "content": {
                "application/json": {}
              }
            }
          }
        }
      },
      "/change-password": {
        "post": {
          "tags": [
            "Users"
          ],
          "summary": "Notifications mercado pago test",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "email": "",
                    "currentPassword": "",
                    "newPassword": ""
                  }
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Successful response",
              "content": {
                "application/json": {}
              }
            }
          }
        }
      },
      "/login": {
        "post": {
          "tags": [
            "Users"
          ],
          "summary": "Return JWT",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "email": "",
                    "password": ""
                  }
                }
              }
            }
          },
          "responses": {
            "201": {
              "description": "Successful response",
              "content": {
                "application/json": {}
              }
            }
          }
        }
      },
      "/profile": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "Devolver product by ID and category ID",
          "security": [
            {
              "bearerAuth": []
            }
          ],
          "responses": {
            "200": {
              "description": "Successful response",
              "content": {
                "application/json": {}
              }
            }
          }
        }
      },
      "/users": {
        "get": {
          "tags": [
            "Users"
          ],
          "summary": "Return All Users",
          "responses": {
            "200": {
              "description": "Succesfull Response",
              "content": {
                "application/json": {}
              }
            }
          }
        },
        "post": {
          "tags": [
            "Users"
          ],
          "summary": "Create User",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "name": "",
                    "lastname": "",
                    "email": "",
                    "password": "",
                    "nationality": ""
                  }
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Succesfull Response",
              "content": {
                "application/json": {}
              }
            }
          }
        }
      }
    }
  }